server:
  port: 19999
spring:
  application:
    name: zuul-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20001/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    user-route:
      service-id: consumer
      path: /consumer/**