# 注册到 eureka server 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20001/eureka/
server:
  port: 20003
spring:
  application:
    name: consumer

feign:
  hystrix:
    enabled: true

